# Development overrides -- extends docker-compose.yml
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  darshjdb:
    build:
      context: .
      target: builder
    environment:
      RUST_LOG: debug
      DDB_WATCH: "true"
    volumes:
      - ./packages/server/src:/build/packages/server/src:ro
      - ./packages/cli/src:/build/packages/cli/src:ro

  postgres:
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@db.darshj.me}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - darshjdb

  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - darshjdb

  grafana:
    image: grafana/grafana:11.1.0
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - darshjdb

volumes:
  prometheus_data:
  grafana_data:
