apiVersion: v2
name: darshjdb
description: A Helm chart for deploying DarshJDB
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - database
  - realtime
  - triple-store
maintainers:
  - name: Darsh Joshi
    url: https://github.com/darshjme
