replicaCount: 1

image:
  repository: ghcr.io/darshjme/darshjdb
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 7700

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: darshjdb.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

postgresql:
  enabled: true
  auth:
    username: darshan
    # Override in production: --set postgresql.auth.password=<secure-value>
    password: darshan
    database: darshjdb
  primary:
    persistence:
      size: 10Gi

env:
  RUST_LOG: info
  DARSHAN_PORT: "7700"
  DARSHAN_ADMIN_DIR: /usr/share/darshan/admin

secrets:
  # Override in production: --set secrets.jwtSecret=<secure-value>
  jwtSecret: change-me-in-production

nodeSelector: {}
tolerations: []
affinity: {}
