apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "darshandb.fullname" . }}
  labels:
    {{- include "darshandb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "darshandb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "darshandb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7700
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "darshandb.fullname" . }}-config
            - secretRef:
                name: {{ include "darshandb.fullname" . }}-secret
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "darshandb.fullname" . }}-secret
                  key: database-url
          livenessProbe:
            httpGet:
              path: /api/admin/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/admin/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
