apiVersion: v1
kind: Secret
metadata:
  name: {{ include "darshjdb.fullname" . }}-secret
  labels:
    {{- include "darshjdb.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  database-url: {{ include "darshjdb.databaseUrl" . | b64enc | quote }}
